server:
  port: 8080
  servlet:
    context-path: /fakeuser
  tomcat:
    uri-encoding: UTF-8
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
    path: /error/serverError # 에러 발생시 path 지정

spring:
#  jsp viewResolver 설정.
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:h2:tcp://localhost/~/springBootBoard
    username: sa
    password:
    driver-class-name: org.h2.Driver

# JPA 설정.
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true

# 로깅 설정.
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
  com:
    atoz_develop:
      mybatissample:
        repository: TRACE

# Mybatis 설정.
mybatis:
  mapper-locations: mybatis/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.allan.springBootBoard.web.board.domain.model, com.allan.springBootBoard.common