server:
  port: 8080
  servlet:
    context-path: /fakeuser
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springBootBoard
    username: sa
    password:
    driver-class-name: org.h2.Driver

# JPA 설정.
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

#  thymeleaf:
#    enabled: false
#    cache: false
#    prefix: classpath:templates/thymeleaf
#    suffix: .html
#    excluded-view-names: jsp/*

  devtools:
    livereload:
      enabled: true

# 로깅 설정.
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
  com:
    atoz_develop:
      mybatissample:
        repository: TRACE

# Mybatis 설정.
mybatis:
  mapper-locations: mybatis/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.allan.springBootBoard.web.board.domain.model, com.allan.springBootBoard.common