server:
  port: 8080
  servlet:
    context-path: /fakeuser
  tomcat:
    uri-encoding: UTF-8
  error:
    include-exception: false # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부
    whitelabel.enabled: true # 서버 오류 발생시 브라우저에 보여줄 기본 오류 페이지 생성 여부
    path: /error/serverError # 에러 발생시 path 지정

spring:
  profiles:
    active: devDB

  #  jsp viewResolver 설정.
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp

  # JPA 설정.
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true

# 로깅 설정.
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace
  com:
    atoz_develop:
      mybatissample:
        repository: TRACE

# Mybatis 설정.
mybatis:
  mapper-locations: mybatis/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.allan.springBootBoard.web.board.domain.model, com.allan.springBootBoard.common

---
# develop Database
spring:
  config.activate.on-profile: devDB

  datasource:
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
# local Database
spring:
  config.activate.on-profile: localDB

  datasource:
    url: jdbc:h2:tcp://localhost/~/springBootBoard
    username: sa
    password:
    driver-class-name: org.h2.Driver
---